baseURL = "https://leandrorosa.github.io/"
languageCode = "en-us"
title = "Leandro Rosa"
theme = "hugo_theme_pickles"
disqusShortname = "leandrorosa"

[params]
twitter = "leandroorosa"
github = "leandrorosa"
